
```{r setup, echo = FALSE, include = FALSE}
library("papaja")
library("knitr") # for knitting things
library("tidyverse") # for all things tidyverse
library("car")
library("lme4")
library("patchwork")
library("effsize")

# these options here change the formatting of how comments are rendered
opts_chunk$set(
  comment = "",
  results = "hold",
  fig.show = "hold")

# set the default ggplot theme 
theme_set(theme_classic())

```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

```{r loading data, warning=FALSE, include=F}
df.demog <- read.csv("../data/PROCESSED_DATA/demog.csv")
df.response <- read.csv("../data/PROCESSED_DATA/response.csv")

ppt.demog_excl_native_lang <- df.demog %>%
  filter(user_lang != "en-US" | (demog_question == "language_first" & demog_response != "Yes")) %>%
  pull(subject_id)

percent_drop = length(ppt.demog_excl_native_lang) / length(unique(df.response$subject_id))

ppt.demog_excl_other_lang <- df.demog %>%
  filter(demog_question == "language_others_fluency" & 
          !is.na(demog_response)) %>%
  filter(demog_response >= 6) %>%
  pull(subject_id)

#TODO; fix this so we don't need to double check subject_id.

 df.demog %>%
   filter(subject_id %in% ppt.demog_excl_other_lang)

percent_drop = length(ppt.demog_excl_other_lang) / length(unique(df.response$subject_id))


df.response <- df.response %>%
  filter(!(subject_id %in% ppt.demog_excl_native_lang),
         !(subject_id %in% ppt.demog_excl_other_lang))

length(unique(df.response$subject)) #132 # no exclusions!
```

```{r}
write.csv(df.response, "../data/PROCESSED_DATA/response_excl.csv")
```

